-- MySQL Script generated by MySQL Workbench
-- 10/11/16 22:48:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema monitoriaifpe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `monitoriaifpe` ;

-- -----------------------------------------------------
-- Schema monitoriaifpe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monitoriaifpe` DEFAULT CHARACTER SET utf8 ;
USE `monitoriaifpe` ;

-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `txt_nome` VARCHAR(60) NOT NULL,
  `txt_email` VARCHAR(60) NOT NULL,
  `txt_cpf` VARCHAR(15) NOT NULL,
  `txt_senha` VARCHAR(200) NOT NULL,
  `txt_sal` VARCHAR(200) NOT NULL,
  `papel_usuario` VARCHAR(1) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `usuario_email_UNIQUE` ON `monitoriaifpe`.`tb_usuario` (`txt_email` ASC);

CREATE UNIQUE INDEX `usuario_cpf_UNIQUE` ON `monitoriaifpe`.`tb_usuario` (`txt_cpf` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_curso` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `txt_descricao` VARCHAR(100) NOT NULL,
  `txt_codigo` VARCHAR(45) NOT NULL,
  `txt_codigo_campus` VARCHAR(45) NOT NULL,
  `txt_grau` ENUM('SUPERIOR', 'TECNICO') NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;

CREATE INDEX `curso_campus_UNIQUE` ON `monitoriaifpe`.`tb_curso` (`txt_codigo_campus` ASC, `txt_codigo` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_aluno` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_aluno` (
  `id_aluno` INT NOT NULL,
  `txt_matricula` VARCHAR(20) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  CONSTRAINT `fk_aluno_usuario`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `monitoriaifpe`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `monitoriaifpe`.`tb_curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `matricula_UNIQUE` ON `monitoriaifpe`.`tb_aluno` (`txt_matricula` ASC);

CREATE INDEX `fk_aluno_usuario_idx` ON `monitoriaifpe`.`tb_aluno` (`id_aluno` ASC);

CREATE INDEX `fk_aluno_curso1_idx` ON `monitoriaifpe`.`tb_aluno` (`id_curso` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_professor` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_professor` (
  `id_professor` INT NOT NULL,
  `txt_siape` VARCHAR(10) NOT NULL,
  `id_curso` INT NOT NULL,
   `assinatura` BLOB,
  PRIMARY KEY (`id_professor`),
  CONSTRAINT `fk_professor_usuario1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `monitoriaifpe`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `monitoriaifpe`.`tb_curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `siape_UNIQUE` ON `monitoriaifpe`.`tb_professor` (`txt_siape` ASC);

CREATE INDEX `fk_professor_usuario1_idx` ON `monitoriaifpe`.`tb_professor` (`id_professor` ASC);

CREATE INDEX `fk_professor_curso1_idx` ON `monitoriaifpe`.`tb_professor` (`id_curso` ASC);

-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_componente_curricular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_componente_curricular` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_componente_curricular` (
  `id_componente_curricular` INT NOT NULL AUTO_INCREMENT,
  `txt_codigo_componente` VARCHAR(45) NOT NULL,
  `txt_descricao` VARCHAR(100) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_componente_curricular`),
  CONSTRAINT `fk_componente_curricular_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `monitoriaifpe`.`tb_curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE INDEX `fk_componente_curricular_curso1_idx` ON `monitoriaifpe`.`tb_componente_curricular` (`id_curso` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_periodo` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `semestre` ENUM('PRIMEIRO', 'SEGUNDO'),
  `ano` INT NOT NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ano_semestre_UNIQUE` ON `monitoriaifpe`.`tb_periodo` (`ano` ASC, `semestre` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_turma` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `turma_ofertada` TINYINT(1) NOT NULL,
  `id_componente_curricular` INT NOT NULL,
  `id_professor` INT NOT NULL,
  `id_periodo` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  CONSTRAINT `fk_turma_componente_curricular1`
    FOREIGN KEY (`id_componente_curricular`)
    REFERENCES `monitoriaifpe`.`tb_componente_curricular` (`id_componente_curricular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `monitoriaifpe`.`tb_professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `monitoriaifpe`.`tb_periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_turma_componente_curricular1_idx` ON `monitoriaifpe`.`tb_turma` (`id_componente_curricular` ASC);

CREATE INDEX `fk_turma_professor1_idx` ON `monitoriaifpe`.`tb_turma` (`id_professor` ASC);

CREATE INDEX `fk_turma_periodo1_idx` ON `monitoriaifpe`.`tb_turma` (`id_periodo` ASC);

CREATE UNIQUE INDEX `componente_professor_periodo_UNIQUE` ON `monitoriaifpe`.`tb_turma` (`id_componente_curricular` ASC, `id_professor` ASC, `id_periodo` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_monitoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_monitoria` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_monitoria` (
  `id_monitoria` INT NOT NULL AUTO_INCREMENT,
  `situacao_monitoria` ENUM('APROVADA', 'AGUARDANDO_APROVACAO', 'REPROVADA') NOT NULL,
  `id_turma` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_monitoria`),
  CONSTRAINT `fk_monitoria_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `monitoriaifpe`.`tb_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitoria_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `monitoriaifpe`.`tb_aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_monitoria_turma1_idx` ON `monitoriaifpe`.`tb_monitoria` (`id_turma` ASC);

CREATE INDEX `fk_monitoria_aluno1_idx` ON `monitoriaifpe`.`tb_monitoria` (`id_aluno` ASC);

-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_atividade` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_atividade` (
  `id_atividade` INT NOT NULL AUTO_INCREMENT,
  `txt_observacao` VARCHAR(140) NULL,
  `txt_descricao` VARCHAR(140) NOT NULL,
  `dt_inicio_atividade` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `dt_fim_atividade` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_monitoria` INT NOT NULL,
  PRIMARY KEY (`id_atividade`),
  CONSTRAINT `fk_atividade_monitoria1`
    FOREIGN KEY (`id_monitoria`)
    REFERENCES `monitoriaifpe`.`tb_monitoria` (`id_monitoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_atividade_monitoria1_idx` ON `monitoriaifpe`.`tb_atividade` (`id_monitoria` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_grupo` ;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `txt_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `txt_descricao_UNIQUE` ON `monitoriaifpe`.`tb_grupo` (`txt_nome` ASC);


-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_usuario_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_usuario_grupo`;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_usuario_grupo` (
	id_usuario INT NOT NULL,
	id_grupo INT NOT NULL,
        PRIMARY KEY (`id_grupo`, `id_usuario`),
        FOREIGN KEY (id_usuario) REFERENCES tb_usuario(id_usuario),
        FOREIGN KEY (id_grupo) REFERENCES tb_grupo(id_grupo)
);

-- -----------------------------------------------------
-- Table `monitoriaifpe`.`tb_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoriaifpe`.`tb_documento`;

CREATE TABLE IF NOT EXISTS `monitoriaifpe`.`tb_documento` (
	txt_hash VARCHAR(64) NOT NULL,
        conteudo MEDIUMBLOB NOT NULL,
	dt_emissao TIMESTAMP NOT NULL,
        PRIMARY KEY (`txt_hash`)
);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `monitoriaifpe`.`tb_grupo` (txt_nome) VALUES('admin');
INSERT INTO `monitoriaifpe`.`tb_grupo` (txt_nome) VALUES('professor');
INSERT INTO `monitoriaifpe`.`tb_grupo` (txt_nome) VALUES('aluno');
INSERT INTO `monitoriaifpe`.`tb_grupo` (txt_nome) VALUES('usuario');


INSERT INTO `monitoriaifpe`.`tb_usuario` (txt_nome, txt_email, txt_cpf, txt_senha, txt_sal, papel_usuario) 
VALUES('Administrador', 'edmilsonsantana82@gmail.com', '23200202092', '0+zTlfvLZCCGoo7b9iOrrAgpzGLXTqwJfj+oq5zr7Qc=', '7A00H/BTG378rmKjiD9IcJw7BIfTVoWiO/64hu04hyI\=', 'U');

INSERT INTO `monitoriaifpe`.`tb_usuario_grupo` (id_usuario, id_grupo) VALUES(1, 1);
INSERT INTO `monitoriaifpe`.`tb_usuario_grupo` (id_usuario, id_grupo) VALUES(1, 4);