DROP DATABASE IF EXISTS MONITORIAIFPE;
CREATE DATABASE MONITORIAIFPE;
USE MONITORIAIFPE;
DROP TABLE IF EXISTS MONITORIAIFPE.USUARIO;
CREATE TABLE MONITORIAIFPE.USUARIO (
	USUARIO_ID INTEGER AUTO_INCREMENT,
	USUARIO_NOME VARCHAR(200) NOT NULL,
	USUARIO_SOBRENOME VARCHAR(200) NOT NULL,
	USUARIO_LOGIN VARCHAR(20) NOT NULL,
	USUARIO_SENHA VARCHAR(40) NOT NULL,
	USUARIO_EMAIL VARCHAR(50) NOT NULL,
        PAPEL_USUARIO VARCHAR(1),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	PRIMARY KEY(USUARIO_ID)
);

DROP TABLE IF EXISTS MONITORIAIFPE.PERIODO;
CREATE TABLE MONITORIAIFPE.PERIODO (
	PERIODO_ID INTEGER NOT NULL AUTO_INCREMENT,
	SEMESTRE ENUM('PRIMEIRO', 'SEGUNDO') NOT NULL,	
	PERIODO_ANO INTEGER NOT NULL,
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	PRIMARY KEY(PERIODO_ID)
);


DROP TABLE IF EXISTS MONITORIAIFPE.CURSO;
CREATE TABLE MONITORIAIFPE.CURSO (
	CURSO_ID INTEGER NOT NULL AUTO_INCREMENT,
	GRAU ENUM('SUPERIOR', 'TECNICO') NOT NULL,	
	CURSO_DS VARCHAR(20) NOT NULL,
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	PRIMARY KEY(CURSO_ID)
);

DROP TABLE IF EXISTS MONITORIAIFPE.PROFESSOR;
CREATE TABLE MONITORIAIFPE.PROFESSOR( 
	PROFESSOR_ID INTEGER,
	PRIMARY KEY(PROFESSOR_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	FOREIGN KEY (PROFESSOR_ID) REFERENCES USUARIO(USUARIO_ID)
);

DROP TABLE IF EXISTS MONITORIAIFPE.DISCIPLINA;
CREATE TABLE MONITORIAIFPE.DISCIPLINA ( 
	DISCIPLINA_ID INT NOT NULL AUTO_INCREMENT,
	PROFESSOR_ID INT,
	DISCIPLINA_DS varchar(200) NOT NULL,
	CURSO_ID INTEGER NOT NULL,
	PRIMARY KEY(DISCIPLINA_ID),
	FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(PROFESSOR_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	FOREIGN KEY (CURSO_ID) REFERENCES CURSO(CURSO_ID)
);


DROP TABLE IF EXISTS MONITORIAIFPE.ALUNO;
CREATE TABLE MONITORIAIFPE.ALUNO (
	ALUNO_ID INTEGER NOT NULL,
	ALUNO_MATRICULA VARCHAR(20) NOT NULL,
	CURSO_ID INTEGER NOT NULL,
	PRIMARY KEY (ALUNO_ID),
	FOREIGN KEY (CURSO_ID) REFERENCES CURSO(CURSO_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	FOREIGN KEY (ALUNO_ID) REFERENCES USUARIO(USUARIO_ID)
);


DROP TABLE IF EXISTS MONITORIAIFPE.DISCIPLINA_ALUNO;
CREATE TABLE MONITORIAIFPE.DISCIPLINA_ALUNO ( 
	ALUNO_ID INT NOT NULL,
	DISCIPLINA_ID INT NOT NULL,
	PRIMARY KEY (ALUNO_ID, DISCIPLINA_ID),
	FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ALUNO_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA(DISCIPLINA_ID)
);

DROP TABLE IF EXISTS MONITORIAIFPE.MONITOR;
CREATE TABLE MONITORIAIFPE.MONITORIA ( 
	MONITOR_ID INT NOT NULL AUTO_INCREMENT,
	ALUNO_ID INT NOT NULL,
	MODALIDADE ENUM('BOLSISTA', 'VOLUNTARIO'),
	DISCIPLINA_ID INT NOT NULL,
	PERIODO_ID INTEGER NOT NULL,
	HABILITADO BOOLEAN NOT NULL,
	HORARIO_ENTRADA VARCHAR(5),
	HORARIO_SAIDA VARCHAR(5),
	PRIMARY KEY(MONITOR_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	FOREIGN KEY(ALUNO_ID) REFERENCES ALUNO(ALUNO_ID),
	FOREIGN KEY(PERIODO_ID) REFERENCES PERIODO(PERIODO_ID),
	FOREIGN KEY(DISCIPLINA_ID) REFERENCES DISCIPLINA(DISCIPLINA_ID)
);


DROP TABLE IF EXISTS MONITORIAIFPE.RELATORIO_FREQUENCIA;
CREATE TABLE MONITORIAIFPE.RELATORIO_FREQUENCIA (
	RELATORIO_ID INT NOT NULL AUTO_INCREMENT,
	RELATORIO_MES INT(2) NOT NULL,
	MONITOR_ID INT NOT NULL,
	SITUACAO_RELATORIO ENUM('APROVADO', 'ESPERA') NOT NULL,	
	PRIMARY KEY (RELATORIO_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
    FOREIGN KEY (MONITOR_ID) REFERENCES MONITORIA(MONITOR_ID)
);

DROP TABLE IF EXISTS MONITORIAIFPE.SEMANA;
CREATE TABLE MONITORIAIFPE.SEMANA(
	SEMANA_ID INT NOT NULL AUTO_INCREMENT,
	SEMANA_DESCRICAO VARCHAR(200),
	SEMANA_OBS VARCHAR(200),
	RELATORIO_ID INT,
	PRIMARY KEY(SEMANA_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	FOREIGN KEY (RELATORIO_ID) REFERENCES RELATORIO_FREQUENCIA(RELATORIO_ID)
);

DROP TABLE IF EXISTS MONITORIAIFPE.ATIVIDADE;
CREATE TABLE MONITORIAIFPE.ATIVIDADE (
	ATIVIDADE_ID INT NOT NULL AUTO_INCREMENT,
	ATIVIDADE_DATA DATE,
	HORARIO_ENTRADA VARCHAR(5),
	HORARIO_SAIDA VARCHAR(5),
	SEMANA_ID INT,
	PRIMARY KEY(ATIVIDADE_ID),
	ULTIMA_ALTERACAO TIMESTAMP DEFAULT current_timestamp() NOT NULL,
	FOREIGN KEY (SEMANA_ID) REFERENCES SEMANA(SEMANA_ID)
);


